export const defaultCurrency = {
  code: 'GBP',
  name: 'British Pound Sterling',
  decimal_digits: 2,
  name_plural: 'British pounds sterling',
  rounding: 0,
  symbol: '£',
  symbol_native: '£',
};

export const defaultCompareCurrencies = [
  {
    code: 'USD',
    name: 'US Dollar',
    decimal_digits: 2,
    name_plural: 'US dollars',
    rounding: 0,
    symbol: '$',
    symbol_native: '$',
  },
  {
    code: 'EUR',
    name: 'Euro',
    decimal_digits: 2,
    name_plural: 'Euros',
    rounding: 0,
    symbol: '€',
    symbol_native: '€',
  },
  {
    code: 'JPY',
    name: 'Japanese Yen',
    decimal_digits: 0,
    name_plural: 'Japanese yen',
    rounding: 0,
    symbol: '¥',
    symbol_native: '￥',
  },
  {
    code: 'CHF',
    name: 'Swiss Franc',
    decimal_digits: 2,
    name_plural: 'Swiss francs',
    rounding: 0,
    symbol: 'CHF',
    symbol_native: 'CHF',
  },
  {
    code: 'CAD',
    name: 'Canadian Dollar',
    decimal_digits: 2,
    name_plural: 'Canadian dollars',
    rounding: 0,
    symbol: 'CA$',
    symbol_native: '$',
  },
  {
    code: 'AUD',
    name: 'Australian Dollar',
    decimal_digits: 2,
    name_plural: 'Australian dollars',
    rounding: 0,
    symbol: 'AU$',
    symbol_native: '$',
  },
  {
    code: 'ZAR',
    name: 'South African Rand',
    decimal_digits: 2,
    name_plural: 'South African rand',
    rounding: 0,
    symbol: 'R',
    symbol_native: 'R',
  },
];
